### ISSUE TITLE
Cake running on Mono can't load netstandard 2.0 assembly

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#2063]
Currently getting `You must add a reference to assembly 'netstandard, Version=2.0.0.0`

Minimal repro:
```
#addin nuget:?package=Microsoft.AspNetCore.TestHost&version=2.0.0&loaddependencies=true
#addin nuget:?package=Microsoft.AspNetCore.Http.Extensions&version=2.0.0&loaddependencies=true

using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Configuration;

Information("Oh hi, Mark!");

new ConfigurationBuilder().Build();
```

Gives:
```
standard.cake(9,28): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

**Comment by dazinator** [comment]
I am hitting what I beleive is this same issue at the moment, after updating cake to 0.26.1 which I had hoped might fix it: https://travis-ci.org/GitTools/GitVersion/jobs/362700883#L1944

**Comment by devlead** [comment]
Which version of mono is used? .NET Standard support was introduced first as preview in like 5.2 and stable in 5.4.

**Comment by dazinator** [comment]
In the travis.yml file is:

`mono: latest`

Should I specify something else?

**Comment by dazinator** [comment]
Will try specifying `5.4.0.201`

**Comment by dazinator** [comment]
Travis doesn't seem to recognise `5.4.0.201` as a valid version of mono.. Have moved thos to a stack overflow question: https://stackoverflow.com/questions/49677894/travis-ci-mono-5-4-0-201

**Comment by devlead** [comment]
@dazinator I've submitted a suggestion on your Stackoverflow question.
